-- Monetary DECIMAL fields in this deployment are interpreted as Nepalese Rupees (NPR).
CREATE DATABASE IF NOT EXISTS medistock CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE medistock;

CREATE TABLE roles (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(40) NOT NULL UNIQUE);
CREATE TABLE users (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, role_id BIGINT UNSIGNED NOT NULL, full_name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (role_id) REFERENCES roles(id));
CREATE TABLE suppliers (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(160) NOT NULL, contact_name VARCHAR(120), phone VARCHAR(40), email VARCHAR(180), lead_time_days INT NOT NULL DEFAULT 7, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE customers (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, customer_code VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(160) NOT NULL, type ENUM('hospital','clinic','pharmacy','other') NOT NULL, credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE products (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sku VARCHAR(40) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, category VARCHAR(90) NOT NULL, manufacturer VARCHAR(140), dosage_form VARCHAR(60), reorder_level INT UNSIGNED NOT NULL DEFAULT 0, tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0, active BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_products_search(name,category));
CREATE TABLE batches (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, product_id BIGINT UNSIGNED NOT NULL, batch_number VARCHAR(70) NOT NULL, expiry_date DATE NOT NULL, quantity INT NOT NULL DEFAULT 0, unit_cost DECIMAL(12,2) NOT NULL, sale_price DECIMAL(12,2) NOT NULL, storage_zone VARCHAR(60), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_product_batch(product_id,batch_number), INDEX idx_batch_fefo(product_id,expiry_date,quantity), FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE sales (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, invoice_number VARCHAR(40) NOT NULL UNIQUE, customer_id BIGINT UNSIGNED NOT NULL, customer_reference VARCHAR(80), total_amount DECIMAL(14,2) NOT NULL, status ENUM('draft','posted','cancelled') NOT NULL DEFAULT 'draft', sold_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, created_by BIGINT UNSIGNED NOT NULL, FOREIGN KEY(customer_id) REFERENCES customers(id), FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE sale_items (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, sale_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, batch_id BIGINT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL, unit_price DECIMAL(12,2) NOT NULL, FOREIGN KEY(sale_id) REFERENCES sales(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(batch_id) REFERENCES batches(id));
CREATE TABLE purchases (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, purchase_number VARCHAR(40) NOT NULL UNIQUE, supplier_id BIGINT UNSIGNED NOT NULL, supplier_invoice VARCHAR(80) NOT NULL, total_amount DECIMAL(14,2) NOT NULL, status ENUM('ordered','partial','received','cancelled') NOT NULL, ordered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, received_at TIMESTAMP NULL, created_by BIGINT UNSIGNED NOT NULL, UNIQUE KEY uq_supplier_invoice(supplier_id,supplier_invoice), FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE purchase_items (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, purchase_id BIGINT UNSIGNED NOT NULL, product_id BIGINT UNSIGNED NOT NULL, batch_id BIGINT UNSIGNED NOT NULL, quantity INT UNSIGNED NOT NULL, unit_cost DECIMAL(12,2) NOT NULL, FOREIGN KEY(purchase_id) REFERENCES purchases(id), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(batch_id) REFERENCES batches(id));
CREATE TABLE inventory_transactions (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, product_id BIGINT UNSIGNED NOT NULL, batch_id BIGINT UNSIGNED NOT NULL, type ENUM('opening','purchase','sale','adjustment','return','writeoff') NOT NULL, quantity INT NOT NULL, reference_type VARCHAR(30), reference_id BIGINT UNSIGNED, reason VARCHAR(255), created_by BIGINT UNSIGNED NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_ledger_product(product_id,created_at), FOREIGN KEY(product_id) REFERENCES products(id), FOREIGN KEY(batch_id) REFERENCES batches(id), FOREIGN KEY(created_by) REFERENCES users(id));
CREATE TABLE audit_logs (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, user_id BIGINT UNSIGNED NOT NULL, action VARCHAR(70) NOT NULL, entity_type VARCHAR(60) NOT NULL, entity_id BIGINT UNSIGNED, details JSON, ip_address VARBINARY(16), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_audit_entity(entity_type,entity_id,created_at), FOREIGN KEY(user_id) REFERENCES users(id));

INSERT INTO roles(name) VALUES ('Administrator'),('Inventory Manager'),('Sales Officer'),('Purchasing Officer'),('Auditor');
